---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 735852179156787201-PxuAMXmW5hWP64eGffBydYhwzHULWQH
:access_token_secret: R11d0mBz2l9VR8NXTPuXv68w50fFAmT6S1HxTUc4N7j40
